### ISSUE TITLE
Transparência no menu principal funcionando incorretamente

### ISSUE THREAD

**Issue by FernandoFMoreira** [FernandoFMoreira/AnaliseFacom#1]
Na página principal do site da Facom, quando selecionado a opção "institucional" ou "Pessoas" e se passa com o cursor sobre "Administração" ou "Estudantes" respectivamente, nota-se que a transparência desses botões é anulada temporariamente.
Ex:
![ex1](https://github.com/FernandoFMoreira/AnaliseFacom/assets/113862553/5c63647f-42ab-472c-84a5-b9a4f63f7b8b)
![ex2](https://github.com/FernandoFMoreira/AnaliseFacom/assets/113862553/c755cb25-fae2-4831-bff0-6307b4322b1d)
![ex3](https://github.com/FernandoFMoreira/AnaliseFacom/assets/113862553/5a05432c-b0b8-404f-b189-4f36c76c2074)
![ex4](https://github.com/FernandoFMoreira/AnaliseFacom/assets/113862553/c590fdb3-421b-47a6-bcc8-f2d1957b2215)

**Comment by tiagoGuidorizzi** [comment]
Isso acontece por que esses itens tem o menu drop down contido neles, então a transparência deles não é um problema, já que ele assume que você vai usar o menu embutido no item, portanto não é um bug
![image](https://github.com/FernandoFMoreira/AnaliseFacom/assets/112420521/ee2d23db-caff-4198-82f1-27c8811d1ab0)
![image](https://github.com/FernandoFMoreira/AnaliseFacom/assets/112420521/a2ce9d2a-5fcb-497c-8927-a3dc811104e6)

**Comment by FernandoFMoreira** [comment]
Realmente, eu vi errado e não percebi, vou fechar a issue já que não faz sentido mantê-la aberta.
